name: Maven Package
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3

    - name: Setup Java JDK
      uses: actions/setup-java@v4.2.1
      with:
        java-version: '17'
        distribution: 'oracle'
        cache: 'maven'

    - name: Run Java Checkstyle
      run: mvn checkstyle:checkstyle

    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
